### ISSUE TITLE
Unable to install

### ISSUE THREAD

**Issue by ashnur** [motemen/gore#70]
`go version go1.6.1 gccgo (GCC) 6.1.1 20160707 linux/amd64`

```
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/ashnur/projects/go"
GORACE=""
GOROOT="/usr"
GOTOOLDIR="/usr/lib/gcc/x86_64-pc-linux-gnu/6.1.1"
GO15VENDOREXPERIMENT="1"
CC="/usr/bin/gcc"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0"
CXX="/usr/bin/g++"
CGO_ENABLED="1"
```

I did what's in the README. Then I run gore and this happens:
```
~ : gore
panic: gccgo importer for custom import path lookup not yet implemented

goroutine 16 [running]:
runtime_dopanic
	/build/gcc/src/gcc/libgo/runtime/panic.c:131
__go_panic
	/build/gcc/src/gcc/libgo/runtime/go-panic.c:111
go_importer.For
	/build/gcc/src/gcc/libgo/go/go/importer/importer.go:35
go_importer.Default
	/build/gcc/src/gcc/libgo/go/go/importer/importer.go:55
main.NewSession
	/home/ashnur/projects/go/src/github.com/motemen/gore/main.go:215
main.main
	/home/ashnur/projects/go/src/github.com/motemen/gore/main.go:60
runtime_main
	/build/gcc/src/gcc/libgo/runtime/proc.c:626

goroutine 17 [syscall]:
	goroutine in C code; stack unavailable
created by runtime_main
	/build/gcc/src/gcc/libgo/runtime/proc.c:598

goroutine 18 [finalizer wait]:
runtime_mcall
	/build/gcc/src/gcc/libgo/runtime/proc.c:295
runfinq
	/build/gcc/src/gcc/libgo/runtime/mgc0.c:2512
kickoff
	/build/gcc/src/gcc/libgo/runtime/proc.c:235
created by runtime_createfing
	/build/gcc/src/gcc/libgo/runtime/mgc0.c:2577

goroutine 19 [syscall]:
	goroutine in C code; stack unavailable
created by os_signal..import
	/build/gcc/src/gcc/libgo/go/os/signal/signal_unix.go:26

goroutine 20 [runnable]:
runtime_mcall
	/build/gcc/src/gcc/libgo/runtime/proc.c:295
bgsweep
	/build/gcc/src/gcc/libgo/runtime/mgc0.c:1833
kickoff
	/build/gcc/src/gcc/libgo/runtime/proc.c:235
created by mgc
	/build/gcc/src/gcc/libgo/runtime/mgc0.c:2215
```

**Comment by motemen** [comment]
Thanks, looks like a bug on 1.6 w/gccgo https://github.com/golang/go/issues/15092. I think upgrading to Go 1.7 or using gc could fix this.
